### ISSUE TITLE
Web page http://cs-studio.sourceforge.net/docbook/ doesn't work

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/org.csstudio.docbook#8]
Web page http://cs-studio.sourceforge.net/docbook/ cannot be accessed.

**Comment by claudio-rosati** [comment]
An error has been encountered in accessing this page.
1. Server: cs-studio.sourceforge.net 
2. URL path: /docbook/ 
3. Error notes: NONE 
4. Error type: 403 
5. Request method: GET 
6. Request query string: NONE 
7. Time: 2016-10-10 07:11:59 UTC (1476083519)

Reporting this problem: The problem you have encountered is with a project web site hosted by SourceForge.net. This issue should be reported to the SourceForge.net-hosted project (not to SourceForge.net).

If this is a severe or recurring/persistent problem, please do one of the following, and provide the error text (numbered 1 through 7, above):

Contact the project via their designated support resources.
Contact the project administrators of this project via email (see the upper right-hand corner of the Project Summary page for their usernames) at user-name@users.sourceforge.net
If you are a maintainer of this web content, please refer to the Site Documentation regarding web services for further assistance.

NOTE: As of 2008-10-23 directory index display has been disabled by default. This option may be re-enabled by the project by placing a file with the name ".htaccess" with this line:

Options +Indexes

**Comment by kasemir** [comment]
Looks like the build failed, so there are no files, http://cs-studio.sourceforge.net/docbook/css_book.pdf for example doesn't exist, and plain browsing (without an index.html) is not permitted.

I get this error when trying to generate the document:

```
html:
    [apply] /Users/ky9/git/org.csstudio.docbook/src/products/products.xml:606: parser error : Entity 'times' not defined
    [apply]             Put 16&times;16, 32&times;32, 48&times;48, 64&times;64, 128&times;128,
    [apply]                          ^

..
    [apply] /Users/ky9/git/org.csstudio.docbook/src/css_book.xml:129: element include: XInclude error : could not load /Users/ky9/git/org.csstudio.docbook/src/products/products.xml, and no fallback was found
```

**Comment by berryma4** [comment]
Odd Jenkins calls the build successful:

```
Buildfile: /scratch/jenkins/workspace/CS-Studio - Docbook/build.xml

clean:

prepare:
    [mkdir] Created dir: /scratch/jenkins/workspace/CS-Studio - Docbook/out

html:
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:606: parser error : Entity 'times' not defined
    [apply]             Put 16&times;16, 32&times;32, 48&times;48, 64&times;64, 128&times;128,
    [apply]                          ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:606: parser error : Entity 'times' not defined
    [apply]             Put 16&times;16, 32&times;32, 48&times;48, 64&times;64, 128&times;128,
    [apply]                                       ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:606: parser error : Entity 'times' not defined
    [apply]             Put 16&times;16, 32&times;32, 48&times;48, 64&times;64, 128&times;128,
    [apply]                                                    ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:606: parser error : Entity 'times' not defined
    [apply]             Put 16&times;16, 32&times;32, 48&times;48, 64&times;64, 128&times;128,
    [apply]                                                                 ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:606: parser error : Entity 'times' not defined
    [apply]             Put 16&times;16, 32&times;32, 48&times;48, 64&times;64, 128&times;128,
    [apply]                                                                               ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:607: parser error : Entity 'times' not defined
    [apply]             and 256&times;256 <filename>.png</filename> files, <filename>.icns</filename>
    [apply]                           ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:608: parser error : Entity 'times' not defined
    [apply]             <filename>.ico</filename>, and a 48&times;48 <filename>.xpm</filename>
    [apply]                                                       ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml:620: parser error : Entity 'times' not defined
    [apply]             16&times;16 icon.
    [apply]                      ^
    [apply] /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/css_book.xml:129: element include: XInclude error : could not load /scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/products/products.xml, and no fallback was found
    [apply] Result: 6
     [copy] Copying 38 files to /scratch/jenkins/workspace/CS-Studio - Docbook/out

pdf:
    [apply] Sep 30, 2016 11:39:15 AM org.apache.fop.cli.Main startFOP
    [apply] SEVERE: Exception
    [apply] org.apache.fop.apps.FOPException: Error attempting to parse XML file (href='products/products.xml').
    [apply] javax.xml.transform.TransformerException: Error attempting to parse XML file (href='products/products.xml').
    [apply]     at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:303)
    [apply]     at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:130)
    [apply]     at org.apache.fop.cli.Main.startFOP(Main.java:177)
    [apply]     at org.apache.fop.cli.Main.main(Main.java:208)
    [apply] Caused by: javax.xml.transform.TransformerException: Error attempting to parse XML file (href='products/products.xml').
    [apply]     at org.apache.xalan.transformer.TransformerImpl.fatalError(TransformerImpl.java:780)
    [apply]     at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:756)
    [apply]     at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1284)
    [apply]     at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1262)
    [apply]     at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:300)
    [apply]     ... 3 more
    [apply] 
    [apply] ---------
    [apply] 
    [apply] ; SystemID: file:/scratch/jenkins/workspace/CS-Studio%20-%20Docbook/src/css_book.xml; Line#: 129; Column#: 44
    [apply] javax.xml.transform.TransformerException: Error attempting to parse XML file (href='products/products.xml').
    [apply]     at org.apache.xalan.transformer.TransformerImpl.fatalError(TransformerImpl.java:780)
    [apply]     at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:756)
    [apply]     at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1284)
    [apply]     at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1262)
    [apply]     at org.apache.fop.cli.InputHandler.transformTo(InputHandler.java:300)
    [apply]     at org.apache.fop.cli.InputHandler.renderTo(InputHandler.java:130)
    [apply]     at org.apache.fop.cli.Main.startFOP(Main.java:177)
    [apply]     at org.apache.fop.cli.Main.main(Main.java:208)
    [apply] 
    [apply] Result: 1

all:
     [echo] === Completed building css_docbook ===

BUILD SUCCESSFUL
Total time: 13 seconds
```

**Comment by kasemir** [comment]
Yes, when I replace `&times;` with just `x` it builds OK.

Claudio, did you somewhere define the `&times;` entity?

Otherwise I'll commit the update with `x`.

**Comment by claudio-rosati** [comment]
OK, it was my fault: I used an entity but I wasn't aware I needed to load it. I'll figure out how to do it (the docbook manual is a bit complex to read and always not very helpful).
By the way, I have to setup locally all it needs to run the build before pushing on GitHub.

**Comment by kasemir** [comment]
Yes, try a local setup to verify changes.
There's something else wrong with the nesting of section tags, note the `<sec2><title>` in here that isn't parsed but shown literally in the output:

![screen shot 2016-10-10 at 9 19 53 am](https://cloud.githubusercontent.com/assets/1932421/19237423/cdb6e4d2-8eca-11e6-90bd-54c258b706c7.png)

**Comment by berryma4** [comment]
Is there a pull request to fix?

**Comment by claudio-rosati** [comment]
Yes, pull request #9 fixed the problem.
I've tested it locally on my Mac, and now everything is working fine.

**Comment by claudio-rosati** [comment]
The broken [page](http://cs-studio.sourceforge.net/docbook/ch16.html) is now online.
I close the issue.

**Comment by berryma4** [comment]
Thank you!
